### ISSUE TITLE
Tooling to guarantee ease book update

### ISSUE THREAD

**Issue by aplanas** [thecodix/book#1]
Even if this effort is about translating the book to Spanish, I would like to comment it in English (is more transparent to other teams, maybe).

So, I think that @goyox86 have some experiences about maintaining the first edition of the book. Also as expressed in this [comment](https://github.com/rust-lang/book/issues/661#issuecomment-314717237) we need to discuss how to work to simplify the maintenance burden of the book. I want to mention that the book (IIUC) will live beyond the NoStarch publication, and that changes in the language will impact in the book.

**Comment by thecodix** [comment]
Agree 100% on use of English for the job

For the second part I have very limited experience so I'll trust on your input to know how to handle this work long term, probably with some collaboration from English fellas

**Comment by goyox86** [comment]
I think it would be good to involve Steve Klabnik here. He might have good advise. Going to Twitter to ping him 😉

**Comment by steveklabnik** [comment]
Hi everyone!

So, there's some good news about maintaining the book. Because the second edition is going to be printed, we actually want to try and change it as little as possible, so that you can compare the online and printed versions and check them out.

What this means is, most new docs go [here](https://github.com/rust-lang/book/blob/master/second-edition/src/appendix-07-newest-features.md), and then, every two-ish years, we merge that stuff back into the main text.

This means that you should have *very* little to do in the main text, except once every two years. And you might have some stuff to do in the meantime, but it will mostly be adding stuff in that one file.

Hopefully that helps! I'm also open to other suggestions on making this easier.

**Comment by thecodix** [comment]
Thanks for the quick answer Steve, sounds much less work if chapters indeed suffer very minor changes

I guess with alerts on the second edition folder we should cover the eventual changes on the source material

Cheers!

**Comment by goyox86** [comment]
Thanks for the update @steveklabnik ! 

I knew you were gonna bring good news ;) Seems straightforward then!
